# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-manual-workflow-approval:
    runs-on: ubuntu-latest

    permissions:
      issues: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Test manual workflow approval
      uses: trstringer/manual-approval@v1
      timeout-minutes: 60
      with:
        secret: ${{ github.TOKEN }}
        approvers: KEC79
        minimum-approvals: 1
        fail-on-denial: true
    
    - name: Post approval step
      run: |
        echo The workflow will now continue after approval is given
