name: Test discoverable workflow

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: 'Enter env name'
        required: true
        type: choice
        options:
          - env1
          - env2

jobs:
  test-manual-workflow-approval:
    runs-on: ubuntu-latest

    steps:
    - name: discoverable workflow run
      run: echo "This is a discoverable workflow run for $env_name"

